version: 2

models:

  - name: stg_churn_rate
    description: "Identifica clientes churned com base na última data de pedido ou ausência de pedidos."
    columns:
      - name: customer_id
        description: "Identificador único do cliente."
        tests:
          - not_null
      - name: is_churned
        description: "Indica se o cliente está churned (1 para churned, 0 caso contrário)."
        tests:
          - not_null

  - name: stg_customers
    description: "Organiza os dados brutos de clientes, incluindo informações de contato e localização."
    columns:
      - name: customer_id
        description: "Identificador único do cliente."
        tests:
          - not_null
          - unique
      - name: company_name
        description: "Nome da empresa associada ao cliente."
        tests:
          - not_null
      - name: contact_name
        description: "Nome do contato principal do cliente."
      - name: contact_title
        description: "Título do contato principal do cliente."
      - name: country
        description: "País associado ao cliente."
        tests:
          - not_null

  - name: stg_orders
    description: "Consolida informações de pedidos, incluindo valores totais e granularidade temporal."
    columns:
      - name: order_id
        description: "Identificador único do pedido."
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Identificador do cliente que fez o pedido."
        tests:
          - not_null
      - name: order_year
        description: "Ano em que o pedido foi realizado."
        tests:
          - not_null
      - name: order_month
        description: "Mês em que o pedido foi realizado."
        tests:
          - not_null
      - name: total_amount
        description: "Valor total do pedido."
        tests:
          - not_null

  - name: stg_sales
    description: "Consolida informações de vendas com granularidade por produto, categoria e período."
    columns:
      - name: product_id
        description: "Identificador único do produto."
        tests:
          - not_null
      - name: product_name
        description: "Nome do produto vendido."
        tests:
          - not_null
      - name: category_id
        description: "Identificador único da categoria do produto."
        tests:
          - not_null
      - name: category_name
        description: "Nome da categoria do produto."
        tests:
          - not_null
      - name: sales_year
        description: "Ano em que as vendas ocorreram."
        tests:
          - not_null
      - name: sales_month
        description: "Mês em que as vendas ocorreram."
        tests:
          - not_null
      - name: total_quantity
        description: "Quantidade total de produtos vendidos."
        tests:
          - not_null
      - name: total_revenue
        description: "Receita total gerada pelas vendas do produto."
        tests:
          - not_null
