version: 2

models:

  - name: stg_order_details
    description: "Tabela intermediária que reúne detalhes de cada pedido, incluindo preço unitário, quantidade, desconto e valor total por item."
    columns:
      - name: order_id
        description: "Identificador único de cada pedido."
        tests:
          - not_null
      - name: product_id
        description: "Identificador único de cada produto."
        tests:
          - not_null
      - name: unit_price
        description: "Preço unitário do produto."
        tests:
          - not_null
      - name: quantity
        description: "Quantidade do produto no pedido."
        tests:
          - not_null
      - name: discount
        description: "Desconto aplicado ao produto."
      - name: total_item_value
        description: "Valor total do item (quantidade x preço unitário - desconto)."
        tests:
          - not_null

  - name: stg_orders
    description: "Tabela principal que consolida informações de pedidos, clientes, funcionários, transportadoras e fornecedores."
    columns:
      - name: order_id
        description: "Identificador único de cada pedido."
        tests:
          - not_null
          - unique
      - name: customer_id
        description: "Identificador único de cada cliente."
        tests:
          - not_null
      - name: customer_country
        description: "País do cliente."
      - name: employee_id
        description: "Identificador único de cada funcionário responsável pelo pedido."
      - name: employee_name
        description: "Nome completo do funcionário."
      - name: employee_title
        description: "Cargo do funcionário."
      - name: employee_region
        description: "Região do funcionário."
      - name: shipper_name
        description: "Nome da transportadora responsável pelo pedido."
        tests:
          - not_null
      - name: shipment_region
        description: "Região de envio do pedido."
      - name: supplier_name
        description: "Nome do fornecedor dos produtos do pedido."
      - name: supplier_country
        description: "País do fornecedor."
      - name: order_date
        description: "Data em que o pedido foi realizado."
        tests:
          - not_null
      - name: required_date
        description: "Data em que o pedido deveria ser entregue."
      - name: shipped_date
        description: "Data em que o pedido foi enviado."
      - name: delivery_time
        description: "Tempo de entrega (dias entre pedido e envio)."
      - name: delivery_cost
        description: "Custo do frete."
      - name: order_year
        description: "Ano em que o pedido foi realizado."
      - name: order_month
        description: "Mês em que o pedido foi realizado."

  - name: stg_sales
    description: "Tabela intermediária que reúne informações de vendas, como produtos, categorias, receita e quantidade por mês e ano."
    columns:
      - name: product_id
        description: "Identificador único de cada produto."
        tests:
          - not_null
      - name: product_name
        description: "Nome do produto vendido."
      - name: category_id
        description: "Identificador único da categoria do produto."
      - name: category_name
        description: "Nome da categoria do produto."
      - name: sales_year
        description: "Ano da venda."
        tests:
          - not_null
      - name: sales_month
        description: "Mês da venda."
        tests:
          - not_null
      - name: total_quantity
        description: "Quantidade total de produtos vendidos."
        tests:
          - not_null
      - name: total_revenue
        description: "Receita total gerada pela venda."
        tests:
          - not_null
